const colorData = {
  mutedColors: [
    { name: 'Coffee with Milk', hex: '#aa8463' },
    { name: 'Pastel Brown', hex: '#6b553e' },
    { name: 'Blue Spruce', hex: '#0c5366' },
    { name: 'Stormy', hex: '#18374d' },
    { name: 'Gray Violet', hex: '#6d7171' },
    { name: 'Twilight Lavender', hex: '#6a4a71' },
    { name: 'Ash Brown', hex: '#645e4b' },
    { name: 'Khaki', hex: '#77744e' },
    { name: 'Dusty Lilac', hex: '#c48da6' },
  ],
  depthLevelColors: [
    { name: 'Deep Water', hex: '#138b99' },
    { name: 'Deep Magenta', hex: '#782e7f' },
    { name: 'Deep Emerald', hex: '#188a6b' },
    { name: 'Imperial Blue', hex: '#212059' },
    { name: 'Twilight Lavender', hex: '#6a4a71' },
  ],
  temperatureColors: [
    { name: 'Dandelion', hex: '#edd700' },
    { name: 'Mustard', hex: '#d0ae2e' },
    { name: 'Hot Coral', hex: '#ef5350' },
    { name: 'Emerald', hex: '#188a6b' },
    { name: 'Ruby', hex: '#9c1017' },
    { name: 'Coral', hex: '#f98754' },
    { name: 'Ash Rose', hex: '#ac5463' },
    { name: 'Sunset Orange', hex: '#f56630' },
    { name: 'Bright Yellow', hex: '#f2f4ca' },
  ],
  saturationColors: [
    { name: 'Bright Pink', hex: '#dc2b65' },
    { name: 'Carnation Pink', hex: '#edadb0' },
    { name: 'Blush Pink', hex: '#fa7d8e' },
    { name: 'Rose Gold', hex: '#f1a8a7' },
    { name: 'Amethyst', hex: '#595a8e' },
    { name: 'Bright Yellow', hex: '#eef289' },
    { name: 'Pastel Magenta', hex: '#c4667b' },
    { name: 'Smoky Orchid', hex: '#c48da6' },
    { name: 'Mint Green', hex: '#6ac098' },
  ],
  bonusColors: [
    { name: 'Chartreuse', hex: '#83cb18' },
    { name: 'Emerald Green', hex: '#188a6b' },
    { name: 'Golden Yellow', hex: '#f2f4ca' },
    { name: 'Spring Green', hex: '#91c169' },
  ],
};

export default colorData;
