
const ColorsEng = {
          "White Lavender": "Белая лаванда",
          "Ivory": "Цвет слоновой кости",
          "Pink Salmon": "Розовый лососёвый",
          "Light Gray Brown": "Светло-серо-коричневый",
          "Pumpkin": "Тыквенный",
          "Sand Beige": "Песочно-бежевый",
          "Coffee with Milk": "Кофе с молоком ",
          "Paprika": "Паприка",
          "Coffee": "Кофе",
          "Carrot": "Морковный",
          "Red-Orange": "Красно-оранжевый",
          "Ochre": "Охра",
          "Saffron": "Шафран",
          "Dandelion": "Одуванчик",
          "Mustard": "Горчичный",
          "Laurel Leaf": "Лавровый лист",
          "Pastel Brown": "Пастельно коричневый",
          "Forest Green": "Лесная зелень",
          "Lime": "Лайм ",
          "Billiard Table": "Бильярдный стол",
          "Customs Uniform": "Таможенная форма",
          "Mint Marshmallow": "Мятный зефир",
          "Sea Wave": "Морская волна",
          "Deep Water": "Глубокая вода",
          "Blue Spruce": "Голубая ель",
          "Stormy": "Грозовой",
          "Warm Lazuli": "Тёплый лазурит",
          "Imperial Blue": "Имперский синий",
          "Southern Night": "Южная ночь",
          "Black Blue": "Черно-синий",
          "Onyx": "Оникс",
          "Quartz": "Кварц",
          "Cosmos": "Космос",
          "Napoleon's Overcoat": "Шинель Наполеона",
          "Gray Violet": "Серо-фиолетовый",
          "Silver": "Серебряный",
          "Condorcet Lilac": "Сирень Кондорсе",
          "Fading Lavender": "Увядающая лаванда",
          "Lavender": "Лаванда",
          "Dark Lavender": "Темно-лавандовый",
          "Dark Fuchsia": "Фуксия тёмная",
          "Purple Violet": "Пурпурная фиалка",
          "Eggplant": "Баклажановый",
          "Hibiscus": "Гибискус",
          "Raspberry": "Малиновый",
          "Pastel Magenta": "Пастельная маджента",
          "Blush Pink": "Розовый румянец",
          "Carnation Pink": "Розовая гвоздика",
          "Pink with Gold": "Розовый с золотом",
          "Coral Pink": "Розовый коралл",
          "Red Coral": "Красный коралл",
          "Ruby": "Рубиновый",
          "Falun Red": "Фалунский красный",
          "Red Brown": "Красно-коричневый ",
          "Bordeaux": "Бордо",
          "Black": "Чёрный",
          "Yellow Earth": "Жёлтая земля",
          "Chartreuse": "Шартрез",
          "Dark Khaki": "Тёмный хакки",
          "Aquamarine": "Аквамарин",
          "Blue Green": "Сине-зелёный",
          "Iris": "Ирис",
          "Coral": "Коралловый",
          "Jungle Green": "Зелёные джунгли",
          "Pine": "Хвойный",
          "Transparent Blue": "Прозрачный голубой",
          "Silver Azure": "Серебряная лазурь",
          "Smoky Orchid": "Дымчатая орхидея",
          "Iceberg": "Айсберг",
          "Dark Olive": "Темно-оливковый",
          "Dark Ochre": "Темная охра",
          "Spicy Chocolate": "Пряный шоколад",
          "Khaki": "Хаки",
          "White Almond": "Белый миндальный",
          "Yellow Beige": "Желто-бежевый",
          "Yellow Umber": "Умбра желтая",
          "Bitter Chocolate": "Горький шоколад",
          "Beige Powder": "Бежевая пудра",
          "Salmon": "Лосось",
          "Desert Sand": "Песок пустыни",
          "Ash Brown": "Пепельно-коричневый",
          "Green Gray": "Зелено-серый",
          "Gray Olive": "Серо-оливковый",
          "Raw Sapphire": "Необработанный сапфир",
          "Royal Blue": "Королевский голубой",
          "Klein Blue": "Синий Кляйна",
          "Twilight Lavender": "Сумеречно-лавандовый",
          "Amethyst": "Аметист",
          "Dusty Lilac": "Пыльная сирень",
          "Turkish Pink": "Турецкий розовый",
          "Tiffany": "Тиффани",
          "Emerald": "Изумруд",
          "Dark Turquoise": "Темная бирюза",
          "Blue Moonstone": "Голубой лунный камень",
          "Red Chestnut": "Красный каштан",
          "Ash Rose": "Пепельная роза",
          "Geraldine": "Джеральдин",
          "Champagne": "Шампанское",
          "Pearl White": "Жемчужный белый",
          "Melissa": "Мелисса",
          "Swamp": "Болотный",
          "Olivine": "Оливин",
          "Spring Green": "Весенняя зелень",
          "Fiery": "Огненный",
          "Petrol": "Петроль",
          "Old Burgundy": "Старое бургундское",
          "Dark Emerald": "Тёмный изумруд",
          "Cardinal Red": "Кардинальский красный",
          "Burgundy Violet": "Бордово-фиолетовый",
          "Indigo": "Индиго",
          "Carmine": "Кармин",
          "Patina": "Патина",
          "Straw": "Соломенный",
          "Grass": "Травяной",
          "Sea Green": "Морской зеленый",
          "Bright Pink": "Ярко розовый",
          "Eggshell": "Яичная скорлупа",
          "Cornflower Blue": "Васильковый",
          "Heavenly Magenta": "Небесная маджента",
          "Wisteria": "Глициния",
          "Unpainted Wool": "Цвет некрашеной шерсти",
          "Cinnabar": "Киноварь",
          "Classic Red": "Классический красный",
          "Terracotta Sand": "Терракотовый песок",
          "Pink Mist": "Розовый туман"
};

export default ColorsEng;
        
      